name: Build and test the application

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: on pull request
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci

    - name: Build
      run: npm run build

    - name: Test
      run: npm run test
